openam-jp/openam

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

Issue #15 Provide templates for contributions
関係者が価値ある作業に注力できるよう、定型的な作業はできるだけ単純化したいです。
IssueやPull-Requestの見出しや体裁を揃えることに割く時間を減らし、コードをより良くする時間に振り替えられたら幸いです。
副次的な効果として、IssueやPull-Requestの質が揃うことで可読性が上がること、GitHubコミュニティプロファイルの評価が上がることを期待しています。
- 「.github」ディレクトリ配下に、規定の名前のテキストファイルを格納する
1. Bug-Issue (bug-report.md)
1. Feature-Issue (feature-request.md)
1. Pull-Request (PULL_REQUEST_TEMPLATE.md)
下記理由から、この方式が利便性が高いと考えました。
- コメントタグは編集中のみ表示され、確定すると非表示となる
- 文字列として埋め込む方式と比べ、「まず削除」の手間が無くなる
- うっかり必要な箇所まで削除しすぎるリスクも減少する
コミュニティの性質上、日本語圏の方が多く参加されると想定され、「予備知識が無くても方針を汲み取りやすいこと」を重視しました。
- 英語文のみだと、英語が不得手な方は見落とす可能性が高いと考えた
- 「タイトル欄は英語で記入頂きたい」旨だけは、日本語も併記した
- その他は、日本語OKの項目は日本語も併記、英語のみの項目は英語のみとした
1. テキスト内容をクリップボードへコピーする
1. 新規Issueや新規Pull-Requestを起票し、テキスト入力欄へペーストする
個人アカウントのリポジトリにて動作確認しました。

Issue #15 Provide templates for contributions

---

openam-core-rest/src/main/java/org/forgerock/openam/core/rest/authn/core/LoginAuthenticator.java
openam-core/src/main/java/com/sun/identity/authentication/service/AuthUtils.java

OpenAM13 の時点では XUI は初回の認証 REST API のみにクエリーパラメーターを付与していた。
そして、OPENAM-8879 の修正(21c70bb)によって XUI は認証 REST API をコールする際に毎回クエリーパラメーター（ForceAuth を含む）を付与するようになった。
しかし、この変更に対してサーバーサイドの処理には変更を行わなかったため、認証ステージの判定に異常をきたしてしまったと考えられる。
LoginAuthenticator.startLoginProcess() は正常時は初回の REST API でしか実行されないが、ForceAuth が付与されていると毎回実行されてしまう。
その結果、認証モジュールのコールバックの先頭の処置が実行されるが、たとえば HOTP 認証では先頭のコールバックが空のため（HOTP.xml 参照）POST された情報と一致せず、JSON コールバックエラーが発生する
内部処理ではセッションアップグレードと判定すると新規リクエスト扱いとなり、LoginAuthenticator.startLoginProcess() を実行してしまう。その
ため、セッションアップグレードの判定を行っている LoginAuthenticator.getAuthContext() を修正する。
N/A
N/A
N/A
N/A
* 「ForceAuth」&「DataStore & HOTP の認証連鎖」の組み合わせで問題が発生しないこと
* セッションがある状態から ForceAuth で再度認証がもとめられること
* 「ForceAuth」&「XUI を無効」の組み合わせで問題が発生しないこと

Issue #7 ForceAuth cause JSON callbacks error

---

legal-oem/THIRDPARTYREADME.txt
legal/THIRDPARTYREADME.txt
openam-entitlements/src/main/java/org/forgerock/openam/entitlement/rest/JsonPolicyParser.java
openam-entitlements/src/main/java/org/forgerock/openam/entitlement/rest/model/json/EntitlementsRegistryTypeIdResolver.java
pom.xml

The version of the Jackson library that OpenAM specifies (2.4.2) is old and may contain vulnerabilities.
Therefore, we should update the value of 'jackson.version' and the source code interface.
Upgrade these libraries that depend on build.
- jackson-annotations, jackson-core, jackson-dataformat-xml -> 2.8.11
- jackson-databind -> 2.8.11.2
- activemq (is used only for unit tests) -> 5.15.6
- Fix method signature mismatch.
- Fix README.
- Build -> Successful.
- Unit testing -> Successful.
- Smoke testing -> Successful.

Issue #21 Upgrade dependencies.

---

openam-core/src/main/java/com/sun/identity/common/ConfigMonitoring.java

In the ConfigMonitoring class, an error occurs if the monitoring configuration is not enable.
```
openam-core/src/main/java/com/sun/identity/common/ConfigMonitoring.java
141         int i = getMonServiceAttrs();
142         if (i != 0) {
143             debug.error(classMethod + "getMonServiceAttrs returns " + i +
144                 ", monitoring disabled");
145             Agent.setMonitoringDisabled();
146             return;
147         }
```
The `i` takes the following value.
* (OK) -> 0
* MON_CONFIG_DISABLED -> -1
* MON_MBEANSRVR_PROBLEM -> -2
* MON_RMICONNECTOR_PROBLEM -> -3
* MON_CREATEMIB_PROBLEM -> -4
* MON_READATTRS_PROBLEM -> -5
We should exclude MON_CONFIG_DISABLED from error.
Cherry picked OPENAM-3415(9ae9637) and OPENAM-9814(b16f43e)
* No error output in CoreSystem debug …

Issue #26 Suppress monitoring error in CoreSystem during OpenAM startup

---

openam-cli/openam-cli-impl/src/main/java/com/sun/identity/cli/datastore/AddAMSDKIdRepoPlugin.java
openam-core/src/main/java/com/sun/identity/idm/common/IdRepoUtils.java
openam-core/src/main/java/com/sun/identity/policy/plugins/LDAPFilterCondition.java
openam-core/src/main/java/com/sun/identity/policy/plugins/LDAPRoles.java
openam-core/src/main/java/org/forgerock/openam/ldap/LDAPAuthUtils.java

LDAP SDK を OpenDJ SDK に変更した際のミスと考えられます。
変更前は LDAP プロトコルの timelimit（秒）として利用されていた設定を OpenDJ SDK に移行する際にミリ秒の設定として扱うようになったことが原因です。
OPENAM-8459 の修正を cherry-pick し、タイムアウトの単位をミリ秒から秒に変更します。
N/A
タイムアウトの単位が秒として正しく扱われるようになりました。
N/A
N/A
* LDAPFilterCondition.java
* LDAP フィルター条件（Policy Configuration Service）の検索タイムアウトを 1 にした場合にポリシー保護下にアクセスできること（修正前はアクセス拒否）
* LDAPAuthUtils.java
* LDAP 認証モジュールの LDAP 操作タイムアウトの設定を 1 にした場合に認証できること（修正前は認証失敗）
* AddAMSDKIdRepoPlugin.java
* コードレビューのみ
* LDAPRoles.java
* コードレビューのみ
N/A

Issue #6 Search Timeout for LDAP filter condition should be in seconds

---

legal-oem/THIRDPARTYREADME.txt
legal/THIRDPARTYREADME.txt
pom.xml

The Commons FileUpload 1.3.1 has the following vulnerabilities.
* CVE-2016-1000031 : File Manipulation/Remote Code Execution
* CVE-2016-3092 : Denial of Service
Upgrade Commons FileUpload to 1.3.3.
It seems that Commons FileUpload is only used in the initial configuration screen. Therefore, the initial configuration screen has been tested.

Issue #24 Upgrade Commons FileUpload library to 1.3.3

---

openam-core/src/main/java/com/sun/identity/authentication/client/AuthClientUtils.java
openam-core/src/main/java/com/sun/identity/authentication/service/AMLoginContext.java

Authentication error messages of REST API are obtained from `LoginState`. LoginState stores the message generated by `AuthClientUtils.getErrorVal()`, but this method only refers to the platform locale.
```
openam-core/src/main/java/com/sun/identity/authentication/client/AuthClientUtils.java
1852     public static String getErrorVal(String errorCode,String type) {
1853 
1854         if (Locale.getDefaultLocale() != bundle.getLocale()) {
1855             bundle = Locale.getInstallResourceBundle(BUNDLE_NAME);
1856         }
```
Create error message from request locale.
N/A
N/A
N/A
Error messages now refer to Accept-Language.
* Authentication Error(DataStore Auth)
* Authentication Session Timedout(This needs translation.json)
* Max Session Count
* Profile Error
* User Incative
* Organization …

Issue #30 Auth Error messages ignore Accept-Language

---

openam-console/src/main/webapp/console/task/CompleteCreateHostedIDP.jsp

Not defined variable is used at corresponding section
Change "frm(not defined variable)" to "document.forms[0](this is written at other partial of same class)" at corresponding section
Press finish button of Identity Provider wizard and confirm the screen change

Issue #10 Finish button of Identity Provider wizard doesn't work

---

openam-core/src/main/java/com/iplanet/am/util/AMSendMail.java

The JavaMail debug option is set to "ture". 
```
193         moduleProps.put("mail.debug", "true");
```
The JavaMail debug option is set to "false". 
JavaMail log is not output to catalina.out when sending mail using HOTP authentication module.

Issue #29 JavaMail debug logs are output to stdout

---

openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/admin/services/realm/AuthenticationService.js
openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/admin/views/realms/authorization/policies/PoliciesView.js
openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/uma/views/resource/BasePage.js

As written at comment of Issue #54, There are three similar problems.
Problem 1) Can not edit policy using IE11 (the main title of Issue #54)
When using IE11 as a client, you can not edit the policy in the admin console.
Problem 2) Can not create authentication module when using IE11
When using IE11 as a client, you can not create authentication module in the admin console.
Problem 3) Can not display user resource information when using IE11 and enabling UMA provider.
When using IE11 and enabling UMA provider, you can not display user resource information at user profile screen.
I modified these three problems.
Each problem information is as follows.
openam/openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/admin/views/realms/authorization/policies/PoliciesView.js
Not encoded …

Issue #54 Can not edit policy using IE11

---

openam-core-rest/src/main/java/org/forgerock/openam/core/rest/sms/SmsCollectionProvider.java

previous code remove all of config tree when remove default module or same name of default module.
new delete process first check if target module is  subConfig.
if module is not subConfig, check target module is default module.
finally, check if default module have subConfig. not have subConfig remove default module config tree.
if module have subConfig remove default module setting only.
if target module is not default but same name of default module, remove that when first check timing.
a.
1. Create a new module instance with a default module
2. Delete default module instance
b.
1. Delete default module instance
2. Create a new module instance same name of default module
3. Delete 2. instance
> We already have a patch for this problem, right?
yes. but that patch is not good.(patch …

Issue #50 Deleting an instance of the authentication module registered by default also deletes the authentication modules of the same type

---

openam-authentication/openam-auth-saml2/src/main/java/org/forgerock/openam/authentication/modules/saml2/SAML2.java

Login Locale is not specified to the new authContext and the default locale is used instead.
Set Login Locale to the new authContext right after it is created.
none
none
none
none
See Issue #47 "Steps to reproduce"
Local authentication screen is displayed in Japanese as expected

Issue #47 Local auth ignores Accept-Language

---

openam-oauth2/src/main/java/org/forgerock/oauth2/core/ResourceOwnerSessionValidator.java

When the user login in more than one chain, in the user session, a value such as `/:chanB|chanA` is stored as the authentication chain information.
OpenAM does not handle such values correctly in ResourceOwnerSessionValidator, so it fails to compare with acr_values.
As a result, OpenAM(OP) returns `acr = 0`.
Parse authentication chain information in user session correctly.
See Issue #42 "Steps to reproduce"

Issue #42  acr_values not working if the user is login in more than one chain

---

openam-oauth2/src/main/java/org/forgerock/oauth2/restlet/ConsentRequiredResource.java
openam-oauth2/src/main/java/org/forgerock/openam/oauth2/OAuth2Utils.java
openam-oauth2/src/main/resources/templates/page/authorize.ftl
openam-oauth2/src/main/resources/templates/popup/authorize.ftl
openam-oauth2/src/main/resources/templates/touch/authorize.ftl

When consent page is needed, page template "authorize.ftl" is used.
In this "authorize.ftl", only "ui_locales" is referred as locale information.
Also, "ConsentRequiredResource.java" which creates data for "authorize.ftl", 
does not refer browser's locale information (Accept-Language header).
On device flow specific page, browser locale information is referred in "DeviceCodeVerificationResource.java". 
And then, this browser locale information data is used in page template "CodeVerificationForm.ftl".
So, add code so as to handle browser locale information,  as the case of device flow specific page mentioned above.
See Issue #61 "Steps to reproduce"

Issue #61 OAuth consent page ignores Accept-Language

---

openam-server-only/src/main/webapp/Debug.jsp
openam-server-only/src/main/webapp/encode.jsp
openam-server-only/src/main/webapp/services.jsp
openam-server-only/src/main/webapp/ssoadm.jsp

Some JSP pages redirect to showServerConfig.jsp when accessing without logging in.
At each JSP files, modify argument of requireAdminSSOToken function from showServerConfig.jsp to each JSP file name.
Access each JSP pages without logging in.
Confirm each JSP pages contents are displayed after logging in.

Issue #85 Some JSPs redirect to showServerConfig.jsp

---

openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/common/models/JSONValues.js

If using IE11, JSONValues.js occurs error  and can not render as expected.
JSONValues.js initializes own data using the argument of the constructor. After that, the data is frozen with the `Object.freeze()` method.
And when creating a realm, `undefined` may be passed as an argument of JSONValues constructor. Then `undefined` is also passed to `Object.freeze()` method.
If the browser supports ES2015, `Object.freeze()` will return `undefined`, and the browser wokes fine. However, an error will occur in IE. Because, IE does not support ES2015.
Check if the argument is `undefined` before calling `Object.freeze()` in JSONValues
* Try #121 "Steps to reproduce"
* Try #121 "Steps to reproduce" using Edge, Chrome, Firefox

Issue #121 Can not create a new realm when using IE11

---

openam-authentication/openam-auth-fr-oath/src/main/java/org/forgerock/openam/authentication/modules/fr/oath/AuthenticatorOATH.java
openam-authentication/openam-auth-fr-oath/src/main/resources/amAuthAuthenticatorOATH.properties
openam-authentication/openam-auth-fr-oath/src/main/resources/amAuthAuthenticatorOATH_ja.properties
openam-server-only/src/main/webapp/config/auth/default_ja/AuthenticatorOATH.xml

'default_ja/AuthenticatorOATH.xml' file does not exist.
Fixed related issues
* Some messages cannot be changed in the properties file
* I want to change the word 'ForgeRock Authenticator (OATH)' that the user sees
* Create 'default_en/AuthenticatorOATH.xml' file
* Some messages can be changed in the properties file
* Changed user-visible message word from 'ForgeRock Authenticator (OATH)' to 'OATH Authenticator'
Changed only in English and Japanese. Because files exist only in these two languages
Test browser language specification in English and Japanese patterns.
Test with on/off pattern of two-factor authentication setting.(Authentication > Setting > General > Two Factor Authentication Mandatory)
* Register the device and login.
* Login with registered device.
* Login using the recovery …

Issue #52 Japanese localization of OATH authentication (FR OATH)

---

openam-audit/openam-audit-configuration/src/main/java/org/forgerock/openam/audit/configuration/AuditServiceConfigurationProviderImpl.java

The realm name cannot be retrieved because the "getRealmNames" method of "AuditServiceConfigurationProviderImpl.java" always returns an empty set. As a result, the realm can't receive notifications and the realm-based log configurations are not applied.
cherry picked from commit f96dd27c67910ef1d8eff763c7f7f209966c39ef.
- Try [#115](https://github.com/openam-jp/openam/issues/115) "Steps to reproduce".

Issue #115 Audit Event Handler ignores realm-based log configurations

---

openam-core-rest/pom.xml
openam-core-rest/src/main/java/org/forgerock/openam/core/rest/session/UnsupportedResponse.java
openam-core/pom.xml
openam-core/src/main/java/org/forgerock/openam/authentication/service/protocol/RemoteHttpServletRequest.java
openam-core/src/main/java/org/forgerock/openam/authentication/service/protocol/RemoteServletRequest.java
openam-core/src/main/java/org/forgerock/openam/authentication/service/protocol/RemoteServletResponse.java
openam-federation/OpenFM/pom.xml
openam-oauth2/pom.xml
openam-push-notification/pom.xml
openam-radius/pom.xml
openam-samples/custom-authentication-module/pom.xml
openam-slf4j/pom.xml
openam-sts/openam-soap-sts/openam-soap-sts-server/pom.xml
pom.xml

openam-jp/forgerock-bom#2
Since last year, security alerts have been sent from GitHub about Maven dependencies.
After forking this BOM project, I noticed alerts fixed in OpenAM were also occurring.
It's annoying to fix the same alert across multiple projects.
- Move dependencies defined in multiple projects to BOM
- Use BOM in each project
- Do not overwrite the dependency version defined in BOM in each project
- If multiple versions of the same library are used, unify them to the new version
Dependency effects are also occurring in other projects.
Obtain the source with modified dependencies in the following order and build
- forgerock-parent
- forgerock-bom
- forgerock-build-tools
- forgerock--i18n-framework
- forgerock-guice
- forgerock-ui
- forgerock-guava
- forgerock-commons
- …

Issue forgerock-bom#2 Promote dependency management by BOM

---

openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/login/RESTLoginHelper.js

For example, if a multi-factor authentication chain is configured, an authentication failure screen will be displayed if the second authentication fails. However, it seems that the login screen is being drawn at the same time. As a result, the screen display becomes unstable.
The authentication process starts from the beginning by clicking the link on the authentication failure screen. There is no need to redraw the login screen when authentication fails.
Do not redraw the login screen when authentication fails.
* Try #137 "Steps to reproduce"

Issue #137 Display of authentication failure screen is unstable

---

openam-console/src/main/java/com/sun/identity/console/task/ConfigureGoogleAppsCompleteViewBean.java
openam-console/src/main/java/com/sun/identity/console/task/ConfigureSalesForceAppsCompleteViewBean.java
openam-console/src/main/java/com/sun/identity/console/task/ConfigureSalesForceAppsFinishWarningViewBean.java
openam-console/src/main/java/com/sun/identity/console/task/RedirectToRealmHomeViewBean.java

After pressing "Finish" button on the Google Apps settings complete page, 
it is expected to redirect to the realm's dashboard page.
But on the corresponding code, NullPointerException occered because 
it failed to acquire realm information.
Fix code to acquire appropriate realm information by using "PageSessionAttribute".
Not only the Gooble Apps setting but also the Salesforce setting has the same problem.
So it is fixed on this branch in the same way.
See Issue #91 "Steps to reproduce"

Issue #91 AMUncaughtException occurs in the configuration screen for Google Apps

---

openam-ui/openam-ui-ria/src/main/js/config/routes/AMRoutesConfig.js
openam-ui/openam-ui-ria/src/main/js/config/routes/admin/GlobalRoutes.js

XUI displays each screen according to the URL pattern of `RoutesConfig`. They are defined as regular expression in some settings, but don't consider the beginning of the string. As a result, it may match the fragment's goto parameter. After that, XUI displays an unexpected screen.
Fix routing rules
* Try #58 "Steps to reproduce" with openam-jp/forgerock-ui#4

Issue #58 Unexpected screen is displayed when the authentication chain fails

---

openam-core/src/main/java/org/forgerock/openam/cts/impl/query/reaper/ReaperConnection.java
openam-core/src/main/java/org/forgerock/openam/cts/impl/query/reaper/ReaperImpl.java
openam-core/src/main/java/org/forgerock/openam/cts/impl/query/reaper/ReaperQuery.java
openam-core/src/main/java/org/forgerock/openam/cts/reaper/CTSReaper.java

The `ReaperConnection` handled by `CTSReaper` closes the LDAP connection when it is determined that there is no entry to be deleted, or when a `CoreTokenException` occurs.
If `ReaperConnection` finds entries to delete and CTS stops in the middle of those deletions, `CTSReaper` exits without `ReaperConnection` closing the LDAP connection.
```
openam-core/src/main/java/org/forgerock/openam/cts/reaper/CTSReaper.java
98         try {
99             long total = 0;
100             query.start();
101             for (Collection<String> ids = reaperQuery.nextPage(); ids != null; ids = reaperQuery.nextPage()) { 
102                 // If the thread has been interrupted, exit all processing.
103                 if (Thread.interrupted()) {
104                     Thread.currentThread().interrupt(); …
```

Issue #88 Expired Token remains in CTS

---

openam-authentication/openam-auth-oidc/src/main/java/org/forgerock/openam/authentication/modules/oidc/JwtHandler.java
openam-authentication/openam-auth-oidc/src/main/java/org/forgerock/openam/authentication/modules/oidc/JwtHandlerConfig.java
openam-authentication/openam-auth-oidc/src/main/java/org/forgerock/openam/authentication/modules/oidc/OpenIdConnectConfig.java
openam-authentication/openam-auth-oidc/src/main/resources/amAuthOpenIdConnect.properties
openam-authentication/openam-auth-oidc/src/main/resources/amAuthOpenIdConnect.xml
openam-console/src/main/java/com/sun/identity/console/agentconfig/AgentDumpViewBean.java
openam-core/src/main/resources/amUpgrade.properties
openam-upgrade/pom.xml
openam-upgrade/src/main/java/jp/co/osstech/openam/upgrade/steps/UpgradeOpenIdConnectAuthModulesStep.java
openam-upgrade/src/main/java/org/forgerock/openam/upgrade/helpers/OpenIdConnectAuthModuleServiceHelper.java

* Adjust agent configuration export page
* cherry-pick OPENAM-9760
* Add client secret field in setting of OIDC id_token bearer authentication

Issue #67 ForgeRock AM/OpenAM Security Advisory 201801-02: Configuration password stored in plain text

---

openam-federation/openam-federation-library/src/main/java/com/sun/identity/saml2/profile/ResponseInfo.java
openam-federation/openam-federation-library/src/main/java/com/sun/identity/saml2/protocol/Response.java
openam-federation/openam-federation-library/src/main/java/com/sun/identity/saml2/protocol/Status.java
openam-federation/openam-federation-library/src/main/java/com/sun/identity/saml2/protocol/StatusCode.java

Deserialization fails because,
- `ResponseInfo` class does not have the default constructor.
- Concrete types for `Response`, `Status` and `StatusCode` interfaces can not be determined during deserialization.
- Add the default constructor to `ResponseInfo`  class.
- Add `@JsonDeserialize(as=...)` annotation to `Response`, `Status` and `StatusCode` interfaces.
During an internal review,  it was point out that interface should not have a reference to its implementation.  Using Jackson MixIn annotations instead would be a better solution.  Since `@JsonDeserialize` is being used in other places in SAML2 module, we decided to do the same for this fix.  We are planning to refactor this module later.
None.
None.
None.
None.
See Issue #40 Steps to reproduce.
SAML2 authentication works when SAML2 …

Issue #40 SAML2 authentication does not work when SAML2 failover is enabled

---

openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/login/RESTLoginView.js
openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/login/tokens/AuthenticationToken.jsm

For example, if a multi-factor authentication chain is configured, an authentication failure screen will be displayed if the second authentication fails.
Because of this specification, `RESTLoginView.js` determines whether the authentication stage is greater than 1 when authentication fails. 
However, this determination does not consider redirect callbacks. If authentication fails after returning from the redirect callback, the authentication stage should be considered 1 or higher.
The redirect callback creates an authId cookie before redirecting. This cookie allows the authentication process to continue after returning to OpenAM. Therefore if the authentication process handled the authId cookie, it can be determined that the redirect was returned. 
This fix changes OpenAM to display an …

Issue #45 Authentication process can not continue if local authentication fails in SAML2 authentication

---

openam-core/src/main/java/org/forgerock/openam/cts/impl/SAML2CTSPersistentStore.java
openam-federation/OpenFM/src/main/java/org/forgerock/openam/authentication/Saml2SessionUpgradeHandler.java

When SAML2 failover is enabled, OpenAM as SAML IdP stores IDPSessionCopy in CTS. 
IDPSessionCopy is information for single logout. 
It contains the SP entity IDs which the SSO token has been federated.
Therefore, OpenAM needs to update IDPSessionCopy every time it issues an assertion, but it is not actually updated.
In the IDPSSOUtil assertion generation process, it seems that `SAML2FailoverUtils.saveSAML2TokenWithoutSecondaryKey()` is called to update IDPSessionCopy.
```
openam-federation/openam-federation-library/src/main/java/com/sun/identity/saml2/profile/IDPSSOUtil.java
878     private static Assertion getAssertion(
...
1110         //  Save to SAML2 Token Repository
1111         try {
1112             if (SAML2FailoverUtils.isSAML2FailoverEnabled()) {
1113                 long …
```

Issue #39 Information for single logout stored in CTS is not updated

---

openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/login/tokens/AuthenticationToken.jsm
openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/login/tokens/SessionToken.jsm

The processing of cookies on XUI has been modularized due to the modification of OPENAM-7996 (dec03c736080738684cbe22183fb5aa2761b9616).
However, these cookie modules are reading the secure flag setting from the wrong variable.
OK -> Configuration.globalData.secureCookie
NG -> Configuration.globalData.auth.secureCookie
* cherry-pick OPENAM-9515 (4657dc7b8f8c2b6f1f203a2cd07e8bc02b407462)
* Try #3 "Steps to reproduce"

Issue #3 XUI does not enable Secure cookie flags for SSO tracking cookie on 13.5.0

---

openam-entitlements/src/main/java/org/forgerock/openam/entitlement/conditions/environment/AMIdentityMembershipCondition.java
openam-entitlements/src/main/java/org/forgerock/openam/entitlement/conditions/environment/ConditionConstants.java
openam-entitlements/src/test/java/org/forgerock/openam/entitlement/conditions/environment/AMIdentityMembershipConditionTest.java
openam-federation/openam-federation-library/pom.xml
openam-federation/openam-federation-library/src/main/java/jp/co/osstech/oam/saml2/plugins/PolicyCheckIDPAdapter.java
openam-server-only/src/main/resources/services/entitlement.xml
openam-ui/openam-ui-ria/src/main/js/config/routes/admin/RealmsRoutes.js
openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/admin/views/realms/authorization/policySets/EditProviderPolicySetView.js
openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/admin/views/realms/authorization/policySets/PolicySetsView.js
openam-ui/openam-ui-ria/src/main/resources/locales/en/translation.json
openam-ui/openam-ui-ria/src/main/resources/locales/ja/translation.json
openam-ui/openam-ui-ria/src/main/resources/templates/admin/views/realms/authorization/policySets/PolicySetsToolbarTemplate.html

See the description section of the Issue #89.
See the solution mentioned in the Issue #89.
This feature is made up of three parts described below:
1. An implementation of `SAML2IdentityProviderAdapter` interface.  Its `preSendResponse` method checks user/session properties against defined policies.
2. A definition of service configuration called `AuthProviderService`.  It is used for creating access policies .
3. Additional parameters used for policy evaluation.  Some env conditions, namely `LDAP filter condition` and `Membership condition` require realm or subject parameters.
A simple configuration guide is attached with this request.
None.
Performance might be affected if complicated access policies need to be applied.
None.
- Set up an IdP and an SP.
- Set up the adapter and define …

Issue #89 Policy based access control for SAML 2.0 IdP (new feature)

---

openam-server-only/src/main/webapp/config/auth/default_ja/OATH.xml

#131
In the OATH authentication module (not the FR OATH authentication module), the implementation and Japanese callback XML are inconsistent. Therefore, if you authenticate with a browser with a Japanese locale, an authentication error will occur even if you enter the correct OTP.
This problem occurs because the processing flow and the callback XML are not consistent.
The module processing flow attempts to return the callback ID “2”.
However, the callback ID “2” does not exist in Japanese callback XML.
In English callback XML, there is no problem because the processing of callback ID “2” exists.
Add processing of callback ID “2” to “default_ja/OATH.xml”.

Issue #131 OATH authentication module(not FR OATH) does not work in Japanese locale

---

openam-server-only/src/main/webapp/assets/css/Specific/wizard.css
openam-server-only/src/main/webapp/assets/css/style.css
openam-server-only/src/main/webapp/config/wizard/step1.htm
openam-server-only/src/main/webapp/config/wizard/step2.htm
openam-server-only/src/main/webapp/config/wizard/step3.htm
openam-server-only/src/main/webapp/config/wizard/step4.htm
openam-server-only/src/main/webapp/config/wizard/step5.htm
openam-server-only/src/main/webapp/config/wizard/step6.htm
openam-server-only/src/main/webapp/config/wizard/step7.htm
openam-server-only/src/main/webapp/config/wizard/wizard.htm

Although Layout depends on a browser, the height and the width of the boxes in the setup tool was inappropriately set fixed.
* Set the maximum height of the boxes. 
* When the required size of the boxes is higher than the reference height, users can scroll the display.
* When not, the height is automatically adjusted.
* Set fixed the appropriate width.
* Performed the fine adjustment.
1. If you have already finished configuring the initial setting, delete or move that data.
2. Access to OpenAM.

Issue #188 Broken layout of setup screen

---

openam-ui/openam-ui-ria/src/main/resources/templates/common/components/tab/TabComponentTemplate.html

#195 
When clicking Tab UI, if the fragment of link url is an empty, an error will occur in JavaScript.
As a result, the selected tab is not highlighted.
I think it may be the effect of changing bootstarp at #135.
Give tab id string to fragment of link url.
(Any string is okay if it is not an empty string)
- See #195 Description
- CONFIGURE > SERVER DEFAULTS
- CONFIGURE > AUTHENTICATION > Core Attributes
- DEPLOYMENT > SERVERS > (Select a server)
- See JavaScript console of the developer tool of the web browser

Issue #195 Tab UI selection is not highlighted on some screens

---

openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/admin/views/realms/authorization/policies/conditions/ConditionAttrDayView.js
openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/admin/views/realms/authorization/policies/conditions/EditEnvironmentView.js
openam-ui/openam-ui-ria/src/main/resources/locales/en/translation.json
openam-ui/openam-ui-ria/src/main/resources/locales/ja/translation.json

The time policy condition uses the translation.json value as the setting data for the day of the week (for example, `console.authorization.common.weekdays.Monday.short`). Therefore, time policy conditions may not work as expected if the browser language setting is other than English.
translation.json is information for localization and should not be used as a setting value.
Define the values for week settings in the JavaScript file. And change the display process for the time policy condition.
Try #199 "Steps to reproduce", and works as "Expected Results".

Issue #199 Policy with day of the week in Japanese does not work

---

legal/THIRDPARTYREADME.txt

THIRDPARTYREADME.txt contains the library license, but it seems to be out of date.
* Update version / copyright information in THIRDPARTYREADME.txt
* Add libraries used by OpenAM, if they does not exist in THIRDPARTYREADME.txt

Issue #197 Update THIRDPARTYREADME.txt for 14 release

---

openam-core/src/main/java/com/sun/identity/policy/plugins/LDAPFilterCondition.java

See #211 and https://bugster.forgerock.org/jira/browse/OPENAM-12037
The `LDAPFilterCondition.java#setPolicyConfig` method in the LDAPFilterCondition adds a new ShutdownListener each time it is called (if cache is disabled or expired), although only one ShutdownListener is needed.
The code to adds a new ShutdownListener exists in two places and is redundant.
1. `com.sun.identity.policy.plugins$LDAPFilterCondition.java#setPolicyConfig`
2. `com.sun.identity.policy.plugins$LDAPConnectionPools#initConnectionPool`
Therefore, remove 1.
Heap usage is significantly reduced in load tests.
In the case of 1,000 accesses per second for 30 minutes, the heap usage before the fix was about 621MB, but after the fix the heap usage improved to 226MB.
- Load test (1,000 accesses per second for 30 minutes)
- …

Issue #211 Memory leak: LDAPFilterCondition creates new ShutdownManager listener on each request

---

openam-oauth2/src/main/java/org/forgerock/oauth2/core/OAuth2ProviderSettings.java

Not clearing claims and scopes cache when OAuth provider configuration is completed.
Clearing hashset of claims and scopes at the organizationConfigChanged method in OAuth2ProviderSettings class.
* Try #138 "Steps to reproduce".
At that time, Test the supported_claims as well.
* Try #138 "Steps to reproduce".
At that time, Test the supported_claims as well.

Issue #138 scopes supported is not hotswap

---

openam-core/src/main/java/com/sun/identity/sm/ServiceConfigImpl.java

A new instance may be created even if a ServiceConfigImpl instance already exists in the cache.
ServiceConfigImpl instance of cache is not released, resulting in memory leak.
Uses the cache unless the ServiceConfigImpl instance is invalid.
* F.Y.I
The fix that frees the cache for the ServiceConfigImpl instance in the specific case that caused it and creates a new one does not work(see https://bugster.forgerock.org/jira/browse/OPENAM-5542)
I tested using the SAML2 authentication module.
Before the fix, 5000 logins generated about 10000 ServiceConfigImpl instances. 
After the fix, it was confirmed that many ServiceConfigImpl instances were not created even with 5000 logins.
Testing with SAML2 authentication module

Issue #224 ServiceConfigImpl causes memory leak

---

openam-authentication/openam-auth-hotp/pom.xml
openam-core/pom.xml
openam-distribution/openam-distribution-diagnostics/pom.xml
openam-distribution/openam-distribution-diagnostics/src/main/assembly/openAMDiagnosticAssembly_Descriptor.xml
openam-entitlements/src/test/java/com/sun/identity/entitlement/xacml3/ResourceAttributeUtilTest.java
openam-schema/openam-diagnostics-schema/pom.xml
openam-schema/openam-idsvcs-schema/pom.xml
openam-schema/openam-jaxrpc-schema/pom.xml
openam-schema/openam-liberty-schema/pom.xml
openam-schema/openam-saml2-schema/pom.xml
openam-schema/openam-wsfederation-schema/pom.xml
openam-schema/openam-xacml3-schema/pom.xml

#219
Newer version of Jackson depend on some Jakarta EE library. And these conflict with the libraries included in this project.
* jakarta.xml.bind-api-2.3.2.jar vs jaxb-api-2.3.0.jar
* jakarta.activation-api-1.2.1.jar vs activation-1.1.jar
But javax.mail depend on Java EE activation. We need to change javax.mail too.
* jaxb-api -> jakarta.xml.bind-api
* activation-> jakarta.activation
* javax.mail -> jakarta.mail
Unit tests works fine.

Issue #219 Upgrade Jackson library to 2.10.x

---

openam-core-rest/src/main/java/jp/co/osstech/openam/core/rest/devices/services/webauthn/WebAuthnDevicesResource.java

The cause is that the argument userName of the searchIdentities method is in DN format(id=demo,ou=user,dc=openam,dc=osstech,dc=co,dc=jp）
The argument of searchIdentities method is the user name(such as "demo").
Internal Server Error does't appear in Dashboard
* FIDO2 (WebAuthn) Authentication Devices is displayed
* FIDO2 (WebAuthn) Authentication Devices can be deleted

Issue #209 Fix Internal server error in Dashboard

---

openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/login/RESTLoginView.js

The callback definition for local authentication of SAML2 authentication module has placeholders as follows. Then, placeholders are replaced according to the authentication chain to be called.
However, many authentications use only a few callbacks. Therefore, some placeholders will remain.
```
<Callbacks length="10" order="3" timeout="120" header="#REPLACE#">
<TextOutputCallback messageType="script">PLACEHOLDER</TextOutputCallback>
<TextOutputCallback messageType="script">PLACEHOLDER</TextOutputCallback>
<TextOutputCallback messageType="script">PLACEHOLDER</TextOutputCallback>
<TextOutputCallback messageType="script">PLACEHOLDER</TextOutputCallback>
<TextOutputCallback messageType="script">PLACEHOLDER</TextOutputCallback>
<TextOutputCallback …
```

Issue #46 the local authentication screen is not focused

---

openam-ui/openam-ui-ria/pom.xml
openam-ui/openam-ui-ria/src/main/assembly/dir.xml

`forgerock-ui-external-libs` has a process to download `CodeMirror` and install it in the Maven local repository.
So the cause is that the downloaded file has changed.
`forgerock-ui-external-libs` installs the new `CodeMirror` archive as a new artifact on Maven.
Then the build process of OpenAM will use the new artifacts.
I have confirmed that the OpenAM build is successful with openam-jp/forgerock-ui#18.

Issue #255 styles-admin.less fails to compile because codemirror.css cannot be found

---

.github/workflows/build_and_release_openam_nightly.yml

#257
Make it easy for anyone interested in this project to get the latest binaries (OpenAM war).
Attach the `nightly` tag to the build artifact and upload it to the `openam-jp/openam/releases` page.
Using GitHub-Actions cron triggers to rebuild the `master` branch source code every day.
I think there are two options: "use the binaries in GitHub-Packages if they are available" and "build everything from source".
I selected "Build everything from source", because one of the important purposes of nightly build is to detect specification changes and situation changes of dependent libraries at an early stage, and easier to operate.
Using the latest Maven, a build error will occur because the following two issues are unresolved.
* https://github.com/openam-jp/opendj/issues/9
* …

Issue #257 Nightly Build

---

openam-oauth2/src/main/java/org/forgerock/openidconnect/OpenIdConnectClientRegistrationService.java
openam-oauth2/src/main/java/org/forgerock/openidconnect/restlet/ConnectClientRegistration.java

see issue#51
Add logic to check Exception and respond with status code 401.
OpenAM responds with HTTP 401 to the OpenID Connect client read request in the following cases.
* Invalid client id
* Don't send access token
* "Access token" setting is empty in client_id. (Agents > OAuth2.0/OpenID Connect Client > "client_id name" > Access Token)
* client_id can be registered with Client Configuration Endpoint.
* client_id can be read with Client Configuration Endpoint.

Issue #51 Client Read Error Response does not conform to the specification

---

openam-authentication/openam-auth-adaptive/src/main/java/org/forgerock/openam/authentication/modules/adaptive/Adaptive.java
openam-authentication/openam-auth-oauth2/src/main/java/org/forgerock/openam/authentication/modules/oauth2/OAuth.java
openam-authentication/openam-auth-oauth2/src/main/java/org/forgerock/openam/authentication/modules/oauth2/OAuthProxy.java
openam-authentication/openam-auth-saml2/src/main/java/org/forgerock/openam/authentication/modules/saml2/SAML2.java

In the current authentication modules (SAML2, OAuth2 and AdaptiveRisk), 
cookies are set only if the setting of the cookie domains is not empty.
Set cookies without domain attribute if the setting of the cookie domains is empty.
[SAML2]
　See Issue #11 "Steps to reproduce"
[OAuth2]
1. Set up OpenAM with OAuth2 authentication module
2. Delete all entries in System -> Platform -> Cookie Domains
3. Call OAuth2 authentication module
4. Authenticate and authorize with OAuth2 Provider
5. (Before correction) Error message "Request not valid" comes out on OAuthProxy.jsp access
(After correction) OAuth2 authentication succeeds
[AdaptiveRisk]
1. Set up OpenAM with AdaptiveRisk authentication module
2. On the AdaptiveRisk authentication module's configuration, use
"Save Cookie Value on Successful …

Issue #11 Several authentication modules do not work if platform cookie domains list is empty.

---

openam-authentication/openam-auth-saml2/src/main/java/org/forgerock/openam/authentication/modules/saml2/SAML2.java
openam-authentication/openam-auth-saml2/src/main/java/org/forgerock/openam/authentication/modules/saml2/SAML2ResponseData.java

With the saml2 authentication module,
sessionindex is required in saml response.
Fix saving sessionindex and null check.
* Try #63 "Steps to reproduce".
* Try #63 "Steps to reproduce".
At that time, in the SalesForce console Enable SingleLogout for SP(OpenAM).
In addition, entere the SingleLogout url and bind.
Then sessionindex is included in the saml response.

Issue #63 SAML2 Auth Module does not accept SAML2 AuthResponse with no SessionIndex

---

.github/workflows/build_and_release_openam_nightly.yml
openam-http-client/pom.xml
openam-oauth2-saml2/pom.xml
openam-oauth2/pom.xml
openam-rest/pom.xml
openam-restlet/pom.xml
openam-sts/openam-soap-sts/openam-soap-sts-server/pom.xml
openam-uma/pom.xml

See #271
Use `https://maven.restlet.talend.com` as Restlet Maven repository
* Build OpenAM
* Make sure that `org.restlet*.jar` hashes match that before the fix

Issue #271 Update Restlet Maven repository

---

openam-authentication/openam-auth-webauthn/pom.xml
openam-authentication/openam-auth-webauthn/src/main/java/jp/co/osstech/openam/authentication/modules/webauthn/WebAuthn4JValidatorImpl.java

Upstream WebAuthn4J stable release is 0.12.0 and OpenAM include release 0.9.14.
Update WebAuthn4J to 0.12.0.
OpenAM RP Server can use stored publickey with old 0.9.14 release.
Registration(No resident key)
Registration(Resident key)
Authentication(No resident key)
Authentication(Resident key)
MFA Authentication
Upgrade OpenAM

Issue #215  Update WebAuthn4J to 0.12.0 release

---

openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/admin/views/realms/authorization/policies/conditions/ConditionAttrArrayView.js
openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/admin/views/realms/authorization/policies/conditions/EditEnvironmentView.js
openam-ui/openam-ui-ria/src/main/resources/locales/en/translation.json
openam-ui/openam-ui-ria/src/main/resources/locales/ja/translation.json

Adding an "Identity membership" environment condition to a policy in the XUI requires specifying entries in the universal Id format.  This is time consuming and prone to making mistakes.
Adding a "Subject condition" to a policy is much easier.  By entering a first few characters, candidates are listed and we only need to choose from them.  "Identity membership" condition should work in the same way.
none
none
none
none
- Editing membership condition using the console
- User CRUD
- Group CRUD
- Membership condition defined in a policy
- User condition works
- Group condition works

Issue #125 An improvement on Membership Condition console

---

.github/workflows/build_and_release_openam_nightly.yml

It turns out that if a Release or Tag already exists, when Actions creates a Release, the status of the Release changes to `Draft`.
After Actions creates the Release, perform an Update to ensure the status is `Draft`.

#288 Fix release page status for Nightly Build

---

openam-core/src/main/java/org/forgerock/openam/upgrade/OpenDJUpgrader.java

See #291
Ignore the buildRevision in OpenDJ version check.
I performed the following tests with openam-jp/opendj#13 .
* Upgrade with OpenAM including new `buildRevision` OpenDJ
* OpenDJ upgrade will be skipped
* Upgrade form 14.0.0 to 15.0.0-SNAPSHOT
* OpenDJ upgrade succeeds

Issue #291 OpenDJ version checks are inconsistent

---

.github/workflows/build_and_release_openam_when_tagged.yml

CI script have been declares constants so that the source it builds is fixed to the HEAD of master branch.
Other things to fix are that the Third party's repository constraints and GitHub-Actions official plugin specifications have changed since the CI script was created.
* Dynamically identify the latest tags.
* Remove declarations of constants fixed to the master branch when determining the source to build.
* Update the parts where it is no longer possible to build or release using the CI script to the current appropriate implementation.

Issue #293 Build the latest tag when tagged

---

.github/workflows/build_and_release_openam_nightly.yml
.github/workflows/build_and_release_openam_when_tagged.yml

Nightly Build workflow uses `ubuntu-latest` image. This image has changed from `22.04` to `24.04`.
Due to this major version upgrade, Chrome cannot enable the sandbox.
Fix Ubuntu version to 22.04.
Run workflow from GUI.

Issue #300 Nightly Build fails in openam-ui-ria
