openam-jp/openam

openam-selfservice/src/main/java/org/forgerock/openam/selfservice/ResourceOwnerOrSuperUserAuthzModuleForKBA.java, openam-selfservice/src/main/java/org/forgerock/openam/selfservice/SelfServiceRestRouteProvider.java
-
ユーザーセルフサービスのエンドポイントに対してセッションを確認するためのクラスを追加しました。
N/A
N/A
N/A
N/A
-
-
=> Issue #19 An improper session management vulnerability in user self-service

openam-core/src/main/java/org/forgerock/openam/oauth2/OAuth2Constants.java, openam-oauth2/src/main/java/org/forgerock/oauth2/core/AuthorizeRequestValidatorImpl.java, openam-oauth2/src/main/java/org/forgerock/oauth2/core/OAuth2Request.java
Add validation of OAuth 2.0 endpoint.
=> Issue #34 Open redirect vulnerability in OAuth 2.0

openam-oauth2/src/main/java/org/forgerock/oauth2/core/OAuth2ProviderSettingsFactory.java, openam-oauth2/src/main/java/org/forgerock/oauth2/core/exceptions/OAuth2ProviderNotFoundException.java, openam-oauth2/src/main/java/org/forgerock/oauth2/restlet/AuthorizeResource.java, openam-oauth2/src/main/java/org/forgerock/openam/oauth2/OpenAMClientRegistrationStore.java
* cherry-pick OPENAM-9360 and OPENAM-9519
* Additional fix for OPENAM-9519
=> Issue #64 ForgeRock OpenAM Security Advisory 201608-01: Open Redirect

openam-core/src/main/java/com/sun/identity/authentication/service/AMLoginContext.java
* Adjust authentication error code
=> Issue #72 ForgeRock AM/OpenAM Security Advisory 201801-07: Information Leakage

openam-oauth2/src/main/java/org/forgerock/oauth2/restlet/AccessTokenFlowFinder.java, openam-oauth2/src/main/java/org/forgerock/openam/oauth2/guice/OAuth2GuiceModule.java
* Disable JWT Bearer Token Authorization Grant
=> Issue #66 ForgeRock AM/OpenAM Security Advisory 201801-01: Business Logic Vulnerability

openam-core-rest/src/main/java/org/forgerock/openam/core/rest/authn/RestAuthenticationHandler.java, openam-core-rest/src/test/java/org/forgerock/openam/core/rest/authn/RestAuthenticationHandlerTest.java
* Do not include input value in exception message
=> Issue #77 ForgeRock AM/OpenAM Security Advisory 201801-12: Content Spoofing Vulnerability

openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/login/LoginFailureView.js
Login failure view remove iPlanetDIrectoryPro when session upgrade failed.
However, this process loses the original session.
* bug
1. Create an instance of ForgeRock Authenticator (OATH)
2. Auth any authentication(e.g. DataStore) and get sessin
3. Access FR OATH module for session upgrade
4. Fail FR OATH authentication
5. Click on the Return to Login Page link on the authentication failure screen
6. Fail FR OATH authentication
7. iPlanetDirectoryPro revoked
* fix
1. Create an instance of ForgeRock Authenticator (OATH)
2. Auth any authentication(e.g. DataStore) and get sessin
3. Access FR OATH module for session upgrade
4. Fail FR OATH authentication
5. Click on the Return to Login Page link on the authentication failure screen
6. Fail FR OATH authentication
7. Stil keep …
=> Issue #57 Session is destroyed when session upgrade fails

openam-oauth2/src/main/java/org/forgerock/oauth2/core/ResourceOwnerSessionValidator.java, openam-oauth2/src/main/java/org/forgerock/openam/oauth2/StatefulTokenStore.java
* Backport OPENAM-9788 (2801dcc)
=> Issue #73 ForgeRock AM/OpenAM Security Advisory 201801-08: Business Logic Vulnerability

openam-core/src/main/java/com/sun/identity/authentication/service/AMAccountLockout.java
Fix memory lockout management algorithm.
=> Issue #109 ForgeRock AM/OpenAM Security Advisory #201901-07: Business Logic Vulnerability

openam-server-only/src/main/webapp/com_sun_web_ui/jsp/help/Masthead.jsp, openam-server-only/src/main/webapp/com_sun_web_ui/jsp/help2/Masthead.jsp, openam-server-only/src/main/webapp/com_sun_web_ui/jsp/version/Masthead.jsp
Add request parameter validation to `Masthead.jsp`.
=> Issue #105 ForgeRock AM/OpenAM Security Advisory #201901-03: Cross Site Scripting (1) `Masthead.jsp`

openam-federation/openam-federation-library/src/main/java/com/sun/identity/saml/common/SAMLUtils.java, openam-federation/openam-federation-library/src/main/java/com/sun/identity/saml/servlet/SAMLAwareServlet.java, openam-federation/openam-federation-library/src/main/java/com/sun/identity/saml/servlet/SAMLPOSTProfileServlet.java
* Change the handling of input parameters in SAML 1.1
* Encode POST redirect URL
* Don't pass target parameter to error page
=> Issue #105 ForgeRock AM/OpenAM Security Advisory 201901-03: Cross Site Scripting (2) SAML1

openam-oauth2/src/main/java/org/forgerock/oauth2/restlet/ExceptionHandler.java, openam-oauth2/src/main/java/org/forgerock/oauth2/restlet/OAuth2RestletException.java
* Encode error_description for OAuth Error page
=> Issue #105 ForgeRock AM/OpenAM Security Advisory 201901-03: Cross Site Scripting (3) OAuth2

openam-core-rest/src/main/java/org/forgerock/openam/core/rest/CoreRestGuiceModule.java, openam-core-rest/src/main/java/org/forgerock/openam/core/rest/CoreRestRouteProvider.java, openam-core-rest/src/main/java/org/forgerock/openam/core/rest/server/ServerInfoResource.java, openam-core-rest/src/test/java/org/forgerock/openam/core/rest/server/ServerInfoResourceTest.java, openam-ui/openam-ui-ria/src/main/js/config/process/AMConfig.js, openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/login/RESTLoginHelper.js, openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/services/AuthNService.js
* Use verified gotoOnFail
* Verify goto parameters at logout
=> Issue #69 ForgeRock AM/OpenAM Security Advisory 201801-04: Open Redirect

openam-console/src/main/java/com/sun/identity/console/task/ConfigureGoogleAppsViewBean.java, openam-console/src/main/java/com/sun/identity/console/task/ConfigureSalesForceAppsViewBean.java, openam-console/src/main/java/com/sun/identity/console/task/CreateFedletViewBean.java, openam-console/src/main/java/com/sun/identity/console/task/model/TaskModel.java, openam-console/src/main/java/com/sun/identity/console/task/model/TaskModelImpl.java
When starting "Configure Google Apps" from one realm's Dashboard page, 
current code check whether there is any cot and idp WITHOUT CONSIDERING the realm.
However the following code assumes there is any cot and idp with the realm, 
so the code throws Exception.
Fix code to check whether there is any cot and idp CONSIDERING the realm.
Not only the Gooble Apps setting but also the Salesforce setting and Fedlet setting have the same problem.
So they are fixed on this branch in the same way.
See Issue #92 "Steps to reproduce"
=> Issue #92 AMUncaughtException occurs in Google Apps settings if there are host IDPs and COTs only in other realms

openam-oauth2/src/main/java/org/forgerock/oauth2/core/AccessTokenService.java, openam-oauth2/src/test/java/org/forgerock/oauth2/core/AccessTokenServiceTest.java
* Add resource owner verification in refresh token grant
=> Issue #71 ForgeRock AM/OpenAM Security Advisory 201801-06: Business Logic Vulnerability

openam-federation/openam-federation-library/src/main/java/org/forgerock/openam/saml2/UtilProxySAMLAuthenticatorLookup.java
* cherry-pick osstech-jp/openam@3a27ed1
=> Issue #80 Authentication bypass

openam-core/src/main/java/com/iplanet/services/ldap/event/LDAPv3PersistentSearch.java
In LDAPv3PersistentSearch class, Retry event is handled by PersistentSearchResultHandler class.
But, SearchResultHandler interface has been changed in OpenDJ SDK 3.0. As a result, no longer handleErrorResult method is called.
We need to implement error handling in another way.
* Move persistent search error handling to ConnectionEventListener
* Try #14 "Steps to reproduce"
=> Issue #14 Persistent search does not recover

legal-oem/THIRDPARTYREADME.txt, legal/THIRDPARTYREADME.txt, openam-scripting/src/test/java/org/forgerock/openam/scripting/AbstractSandboxTest.java, openam-scripting/src/test/java/org/forgerock/openam/scripting/GroovySandboxTest.java, openam-scripting/src/test/java/org/forgerock/openam/scripting/JavascriptSandboxTest.java
This issue may be due to the following issue with Groovy Sandbox.
* Infinite loop when trying to write a for-loop (Issue 16)
* MissingPropertyException in loop with binding variable (Issue 17)
* Update Groovy Sandbox to 1.9 (Groovy is also updated)
* Try #53 "Steps to reproduce"
* Check for additional issue mentioned in https://github.com/openam-jp/openam/issues/53#issuecomment-483500729
* Unit test
```
mvn test -f openam-scripting -Dtest=GroovySandboxTest
```
=> Issue #53 Groovy script causes infinite loop

openam-oauth2/src/main/java/org/forgerock/oauth2/core/AccessTokenVerifier.java, openam-oauth2/src/main/java/org/forgerock/oauth2/core/TokenInfoService.java, openam-oauth2/src/main/java/org/forgerock/oauth2/core/TokenStore.java, openam-oauth2/src/main/java/org/forgerock/openam/oauth2/OpenAMTokenStore.java, openam-oauth2/src/main/java/org/forgerock/openam/oauth2/StatefulTokenStore.java, openam-oauth2/src/main/java/org/forgerock/openam/oauth2/StatelessCheck.java, openam-oauth2/src/main/java/org/forgerock/openam/oauth2/StatelessTokenStore.java, openam-oauth2/src/main/java/org/forgerock/openam/oauth2/guice/OAuth2GuiceModule.java, openam-oauth2/src/main/java/org/forgerock/openam/oauth2/rest/TokenRevocationResource.java, openam-oauth2/src/test/java/org/forgerock/openam/oauth2/StatefulTokenStoreTest.java
* Revert OPENAM-8774
* Revert OPENAM-6534
* Add an argument to TokenStore.read()
=> Issue #70 ForgeRock AM/OpenAM Security Advisory 201801-05: Business Logic Vulnerability

openam-oauth2/src/main/java/org/forgerock/oauth2/core/OAuth2Request.java, openam-oauth2/src/main/java/org/forgerock/openam/oauth2/OpenAMScopeValidator.java, openam-oauth2/src/main/java/org/forgerock/openam/oauth2/StatefulTokenStore.java, openam-oauth2/src/test/java/org/forgerock/openam/oauth2/StatefulTokenStoreTest.java, openam-oauth2/src/test/java/org/forgerock/openam/openidconnect/OidcClaimsExtensionTest.java, openam-oauth2/src/test/resources/oidc-claims-extension.groovy, openam-scripting/src/main/groovy/oidc-claims-extension.groovy
* Filter claims request parameter
* Store validated scopes in request
* Suppress to store claims parameter to authorization code or device code
* Drop the processing for value qualifier of claims
=> Issue #75 ForgeRock AM/OpenAM Security Advisory 201801-10: LDAP Injection Vulnerability

.github/workflows/build_and_release_openam_when_tagged.yml
Add a CI script `build_and_release_openam_when_tagged.yml` for GitHub-Actions.
If detects that a new tag has been added, it adds the Release and adds the assets into it.
=> Add CI script for release

openam-rest/src/main/java/org/forgerock/openam/rest/RealmContextFilter.java, openam-rest/src/test/java/org/forgerock/openam/rest/RealmContextFilterTest.java
* Drop request parameter from exception
=> Issue #226 Cross Site Scripting (XSS) vulnerability

openam-federation/OpenFM/src/main/java/com/sun/identity/workflow/ConfigureGoogleApps.java
hosted idp properties is updated when we configure GoogleApps(Google Workspace) as remote sp.
Remove updateIDPMeta in ConfigureGoogleApps
None
None
None
None
1. Create Hosted Identity Provider
1. Setting ` unspecified ` NameID-Format map value.  Ex.) ` urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified=mail `
1. Configure GoogleApps
1. Check NameID-Format map value is not updated
=> Issue #228 ConfigureGoogleApps remove configured 'unspecified' NameID value map

openam-core/src/main/java/com/iplanet/dpro/session/service/SessionCount.java, openam-core/src/main/java/com/iplanet/dpro/session/service/SessionRequestHandler.java, openam-core/src/main/java/com/iplanet/dpro/session/service/SessionService.java
Validate the requestor's session at GetSessionCount.
=> Issue #251 Broken Access Control

openam-ui/openam-ui-ria/src/main/js/config/process/AMConfig.js, openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/login/RESTLoginHelper.js
Fix Open Redirect vulnerability at logout url.
=> Issue #259 Open Redirect Vulnerability

openam-ui/openam-ui-ria/src/main/js/config/AppConfiguration.js, openam-ui/openam-ui-ria/src/main/js/org/forgerock/openam/ui/user/login/RESTLoginView.js
Login screen can not be displayed with error as "The partial login/_SelfService could not be found", if loading of _SelfService.html (asynchronous processing) is delayed
I fix like Render login screen after asynchronous processing is finished
Confirm that Login screen display if loading of _SelfService.html is delayed
=> Issue #111 Login screen can not be displayed if loading of _SelfService.html is delayed

openam-radius/openam-radius-server/src/main/java/org/forgerock/openam/radius/server/config/RadiusServiceConfig.java
Remove the process of obtaining sensitive data for logging.
=> Issue #282 Sensitive Data Exposure

openam-federation/openam-federation-library/src/main/java/com/sun/identity/saml/common/SAMLUtils.java
#286
Deny unsigned SAML response.
=> Issue #286 SAMLv1.x SSO process vulnerability

openam-oauth2/src/main/java/org/forgerock/oauth2/core/OAuth2ProviderSettings.java
Restrict class resolution in FreeMarker.
=> Issue #298 CVE-2024-41667

openam-federation/openam-federation-library/src/main/java/com/sun/identity/saml2/profile/IDPSSOUtil.java
Fix COT cache manipulation process.
=> Issue #304 CVE-2025-8662
